accounts/urls.py
from . import views
from django.urls import path
from .views import UserEditView, myprofile, signup

app_name = 'accounts'

urlpatterns = [
    path('myprofile/', myprofile, name='myprofile'),
    path('signup/', signup, name='signup'),
    path("customer_service", views.contact, name="customer_service"),
    path('edit_profile/', UserEditView.as_view(), name='edit_profile'),
    path("wishlist", views.wishlist, name="wishlist"),
    path('wishlist/add_to_wishlist/<str:id>',
         views.add_to_wishlist, name='user_wishlist'),
]

cart/urls.py
from struct import pack
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/',
         views.full_remove, name='full_remove')

]

clothing_store/urls.py
from . import views
from newsletter.api import api_add_subscriber
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop.views import product_detail, category_detail, review_rate, Shop__All__Products

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('vendors/', include('vendors.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('vouchers/', include('vouchers.urls')),
    path('review/', review_rate, name='review'),
    path('api/add_subscriber/', api_add_subscriber, name='api_add_subscriber'),


    # SHOP
    path('shop_products', Shop__All__Products.as_view(), name='shop_products'),

    # SHOP

    path('<slug:category_slug>/<slug:slug>/',
         product_detail, name='product_detail'),
    path('<slug:slug>/',
         category_detail, name='category_detail'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/models.py
import uuid
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from vendors.models import Vendor
from vouchers.models import Voucher
from io import BytesIO
from PIL import Image
from django.core.files import File
from django.utils.text import slugify 


class Category(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    parent = models.ForeignKey(
        'self', related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(default="", max_length=255)
    ordering = models.IntegerField(default=0)
    is_featured = models.BooleanField(default=False)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'categories'
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/%s/' % (self.slug)


class Product(models.Model):
    MEDIUM = "M"
    YELLOW = "Yellow"
    COLOR = (("Yellow", 'Yellow'), ("Red", 'Red'), ("Green", 'Green'), ("Orange", 'Orange'), ("Black", 'Black'))
    SIZE = (("XL", 'XL'), ("L", 'L'), ("M", 'M'), ("S", 'S'), ("XS", 'XS'))
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    category = models.ForeignKey(
        Category, related_name='products', on_delete=models.CASCADE)
    vendor = models.ForeignKey(
        Vendor, blank=True, null=True, related_name='products', on_delete=models.CASCADE)
    parent = models.ForeignKey(
        'self', related_name='variants', on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='uploads/', blank=True, null=True)
    image1 = models.ImageField(upload_to='uploads/', blank=True, null=True)
    image2 = models.ImageField(upload_to='uploads/', blank=True, null=True)
    image3 = models.ImageField(upload_to='uploads/', blank=True, null=True)
    width = models.FloatField(default=300)
    length = models.FloatField(default=300)
    stock = models.IntegerField()
    size = models.CharField(max_length=6,choices=SIZE,default=MEDIUM, null=True)
    color = models.CharField(max_length=20,choices=COLOR,default=YELLOW, null=True)
    available = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)
    slug = models.SlugField(default="", max_length=255)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(default=timezone.now)
    visits = models.IntegerField(default=0)
    last_visit = models.DateTimeField(blank=True, null=True)
    voucher = models.ForeignKey(
        Voucher, default='', blank=True, null=True, on_delete=models.CASCADE)
    users_wishlist = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='user_wishlist', blank=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/%s/%s/' % (self.category.slug, self.slug)


class Review(models.Model):
    user = models.ForeignKey(
        User, related_name='review',  on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name='review', on_delete=models.CASCADE)
    comment = models.TextField(max_length=250, blank=True, null=True)
    stars = models.IntegerField(default=0)
    date_added = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.id)

shop/views.py
from uuid import UUID
from django.shortcuts import render, get_object_or_404, redirect
from cart.models import Cart
from order.models import Order
from .models import Category, Product, Review
from datetime import datetime
import random
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.shortcuts import get_object_or_404
from django.views.generic import ListView


def product_detail(request, category_slug, slug):
    product = get_object_or_404(Product, slug=slug)
    product.visits = product.visits + 1
    product.last_visit = datetime.now()
    product.save()

    if request.method == 'POST' and request.user.is_authenticated:
        stars = request.POST.get('stars', 3)
        comment = request.POST.get('content', '')

        review = Review.objects.create(
            product=product, user=request.user, stars=stars, comment=comment)

        return redirect('product_detail', category_slug=category_slug, slug=slug)

    related_products = list(product.category.products.filter(
        parent=None).exclude(id=product.id))

    if len(related_products) >= 5:
        related_products = random.sample(related_products, 5)

    if product.parent:
        return redirect('product_detail', category_slug=category_slug, slug=product.parent.slug)

    context = {
        'product': product,
        'related_products': related_products
    }

    return render(request, 'product_detail.html', context)


def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = category.products.filter(parent=None)

    context = {
        'category': category,
        'products': products
    }

    return render(request, 'category_detail.html', context)



def review_rate(request):
    if request.method == "GET":
        prod_id = request.GET.get('prod_id')
        product = Product.objects.get(id=prod_id)
        comment = request.GET.get('comment')
        rate = request.GET.get('rate')
        user = request.user
        Review(user=user, product=product, comment=comment, rate=rate).save()
        return redirect('product_detail', id=prod_id)



class Shop__All__Products(ListView):
    model = Product

    def get(self, request, category_id=None):
        category = None
        products = None
        if category_id !=None:
            category = get_object_or_404(Category, id = category_id)
            products = Product.objects.filter(category = category, available=True)
        else:
            products = Product.objects.all().filter(available=True)

        ''' Pagination Code '''
        paginator = Paginator(products, 15)
        try:
            page = int(request.GET.get('page', '1'))
        except:
            page = 1
        try:
            products = paginator.page(page)
        except (EmptyPage, InvalidPage):
            products = paginator.page(paginator.num_pages)
        
        ''' End Pagination Code'''

        return render(request,"shop.html",{'category':category, 'products':products})   

shop/templates/category_detail.html
{% extends 'base.html' %}

{% block title %}{{ category.name }} | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul class="bread">
            <li><a href="/">Home</a></li><span>&#x22D9;</span>
            {% if category.parent %}
                <li><a href="{% url 'category_detail' category.parent.slug %}">{{ category.parent.name }} <span>&#x22D9;</span></a></li>
            {% endif %}
            <li class="is-active"><a href="{% url 'category_detail' category.slug %}">{{ category.name }} <span>&#x22D9;</span></a></li>
        </ul>
    </nav>


    <section class="accessory section main__container" id="accessory">
        <h2 class="section-title">{{ category.name }}<span> Category</span></h2>
        
        {% if category.children.all %}
        <div class="accessory__container main__grid">
            {% for subcategory in category.children.all %}
            <div class="accessory__content dcol">
                <img src="./.././static/images/woman.webp" alt="" class="accessory__img">
                <div class="dcol__description">
                <h3 class="accessory__title">{{ subcategory.name }}</h3>
                <a href="{% url 'category_detail' subcategory.slug %}">View products</a>
                </div>
                
            </div>
            {% endfor %}
        </div>
        {% else %}
        {% with products as list_products %}
            {% include 'parts/product_list.html' %}
        {% endwith %}
    {% endif %}
    </section>
{% endblock %}

shop/templates/shop.html
{% extends 'base.html' %}

{% block title %}The Clothing Shop | Shop Page {% endblock %}

{% block content %}


<section class="section  main__container">
    <div class="small_container">
        <!--         SORTING-SELECTOR           -->
       <div class="all__products">
           <h2 class="section-title">All Products</h2>
           <select name="#">
               <option value="">Default Sorting</option>
               <option value="">Sort by price</option>
               <option value="">Sort by popularity</option>
               <option value="">Sort by rating</option>
               <option value="">Sort by Sale</option>
           </select>
       </div>

</section>

<section class="accessory section bd-container" id="accessory">
    <div class="main__container container__grid ">
        <div class="row">
           
            <div class="accessory__container container__grid shop__container">
                {% for p in products %}
                <div class="accessory__content">
                    
                        {% if p.image %}
                        <img src="{{ p.image.url}}" alt="" class="accessory__img">
                        {% else %}
                        <img src="./static/images/girl.webp" alt="" class="accessory__img">

                        {% endif %}
                    <div class="details">
                            <h4 class="accessory__title"><a href="{% url 'product_detail' p.category.slug p.slug %}">{{ p.name|truncatechars:17 }}</a> </h4>
                            <span class="accessory__preci">${{ p.price }}</span>
                            <a href="{% url 'accounts:user_wishlist' p.id %}" class="main__button accessory__button1"><i class='bx bx-heart'></i></a>
                            <a href="{% url 'cart:add_cart' p.id %} " class="main__button accessory__button2"><i class='bx bx-shopping-bag'></i></a>
                    </div>
                </div>
                {% endfor %}
            </div> 
        </div>
        
               
<div class="pagination__container product__quantity">
    {% if products.paginator.num_pages > 1 %}
   
        <div class="pagination_button">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="main__button {% if products.number == pg %}active{% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
    {% endif %}
</div>
      
    </div>
 </section>




 <!--========== EXPLORE ==========-->
<section class=" section">
    <div class="subscribe__container explore__container main__container container__grid">
        <div class="explore__content">
            <h2 class="section-title-center subscribe__title">Own an online shop <br>fully customized for you <br>and
                pay a
                token for sales</h2>
            <a href="#" class="main__button">Shop Now &#8594;</a>
        </div>

        <div class="explore">

        </div>
    </div>
</section>

 {% endblock content %}