cart/urls.py
from struct import pack
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/',
         views.full_remove, name='full_remove')

]

clothing_store/urls.py
from . import views
from newsletter.api import api_add_subscriber
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop.views import product_detail, category_detail, review_rate, Shop__All__Products

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('vendors/', include('vendors.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('vouchers/', include('vouchers.urls')),
    path('review/', review_rate, name='review'),
    path('api/add_subscriber/', api_add_subscriber, name='api_add_subscriber'),


    # SHOP
    path('shop_products', Shop__All__Products.as_view(), name='shop_products'),

    # SHOP

    path('<slug:category_slug>/<slug:slug>/',
         product_detail, name='product_detail'),
    path('<slug:slug>/',
         category_detail, name='category_detail'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from django.urls import path
from . import views
from .views import orderHistory, orderDetail

app_name='order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', orderHistory.as_view(), name='order_history'),
    path('<int:order_id>/', orderDetail.as_view(), name='order_detail'),
]

order/models.py
from django.utils import timezone
from django.db import models

from vendors.models import Vendor


class Order(models.Model):
    first_name = models.CharField(max_length=75, null=True, blank=True)
    last_name = models.CharField(max_length=75, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    place = models.CharField(max_length=100, null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    paid_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    token = models.CharField(max_length=250, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Order Total')
    emailAddress = models.EmailField(max_length=250, blank=True, verbose_name='Email Address')
    vendors = models.ForeignKey(
        Vendor, blank=True, null=True, related_name='orders', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    billingName = models.CharField(max_length=50, blank=True)
    billingAddress1 = models.CharField(max_length=100, blank=True)
    billingCity = models.CharField(max_length=25, blank=True)
    billingPostcode = models.CharField(max_length=10, blank=True)
    billingCountry = models.CharField(max_length=50, blank=True)
    shippingName = models.CharField(max_length=50, blank=True)
    shippingAddress1 = models.CharField(max_length=250, blank=True)
    shippingCity = models.CharField(max_length=25, blank=True)
    shippingPostcode = models.CharField(max_length=10, blank=True)
    shippingCountry = models.CharField(max_length=50, blank=True)

    class Meta:
        db_table = 'Order'
        ordering = ['-created']

    def __str__(self):
        return str(self.id)


class OrderItem(models.Model):
    ACCEPTED = "Accepted"
    ORDER_STATUS = (
    ("Accepted", 'Accepted'), ("Packed", 'Packed'), ("On The Way", 'On The Way'), ("Delivered", 'Delivered'),
    ("Cancel", 'Cancel'))
    product = models.CharField(max_length=50)
    size = models.CharField(max_length=50, default='', null=True)
    color = models.CharField(max_length=50, default='', null=True)
    status = models.CharField(max_length=15, choices=ORDER_STATUS, default=ACCEPTED)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Price')
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor, related_name='items', on_delete=models.CASCADE)
    vendor_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = 'OrderItem'

    def sub_total(self):
        return self.quantity * self.price

    def __str__(self):
        return self.product

order/views.py
import email
import re
from django.shortcuts import render, get_object_or_404
from .models import Order, OrderItem
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View

def thanks(request, order_id):
    if order_id:
        customer_order = get_object_or_404(Order, id=order_id)
    return render(request, 'thanks.html', {'customer_order': customer_order})

class orderHistory(LoginRequiredMixin,View):
    def get(self , request):
        if request.user.is_authenticated:
            email = str(request.user.email)
            order_details = Order.objects.filter(emailAddress=email)
        return render(request, 'order/orders_list.html', {'order_details': order_details})

class orderDetail(LoginRequiredMixin,View):
    def get(self,request, order_id):
        if request.user.is_authenticated:
            email = str(request.user.email)
            order = Order.objects.get(id=order_id, emailAddress=email)
            order_items = OrderItem.objects.filter(order=order)
        
        return render(request, 'order/order_detail.html', {'order': order, 'order_items': order_items})

order/templates/order/order_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Order Details - The Clothing Store
{% endblock %}
{% block content %}

<section class="accessory section bd-container" id="accessory">
    <div class="category__container   main__container container__grid">
        <div>
            <div class="text-center">
            <br>
            <h1 class="text-center my_title">Order Details</h1>
            <br>
    <table class="table table-bordered">
                        <tr>
                            <td class="text-left" colspan="2">
                                <b>Order: </b>#{{ order.id }}<br>
                                <b>Date: </b>{{ order.created|date:"d M Y" }}<br>
                                <b>Order Total: </b>€{{ order.total }}<br>
                                <b>Order Status: </b><i class="fas fa-check"></i> Complete.
                            </td>
    
                            <td class="text-left" colspan="2">
                                <b>Billing Address: </b><br>
                                {{ order.billingName }}<br>
                                {{ order.billingAddress1 }}<br>
                                {{ order.billingCity }}<br>
                                {{ order.billingPostcode }}<br>
                                {{ order.billingCountry }}<br>
                            </td>
                        </tr>
                        <tr>
                                <td><b>Product Description</b></td>
                                <td><b>Qty</b></td>
                                <td><b>Unit Price</b></td>
                                <td><b>Sub-Total</b></td>
                        </tr>
                        {% for item in order_items %}
                        <tr>
                                <td>{{ item.product }}</td>
                                <td>{{ item.quantity }}</td>
                                <td>€{{ item.price }}</td>
                                <td>€{{ item.sub_total }}</td>
                        </tr>
                        {% endfor %}
                       
                        <tr>
                                <td class="text-right" colspan="3"><b>Total Paid</b></td>
                                <td>€{{ order.total }}</td>
                        </tr>
                        <tr>
                            <td class="text-left" colspan="2">
                                <b>Shipping Address: </b><br>
                                {{ order.shippingName }}<br>
                                {{ order.shippingAddress1 }}<br>
                                {{ order.shippingCity }}<br>
                                {{ order.shippingPostcode }}<br>
                                {{ order.shippingCountry }}<br>
                            </td>
                            <td class="text-left" colspan="2">
                                <b>Payment Details: </b><br>
                                The order #{{ order.id }} has been paid successfully via Stripe.
                        </td>
                    </tr>
            </table>
            <button style="background-color: #007bff; padding-right: 2%;"class="btn btn-secondary" onclick="window.print();"><i class="fas faprint"></i>Print Order</button>
           </div>
        </div>
        <br>
        <br>
    
    </div>
    </section>
    



    {% endblock %}

order/templates/order/orders_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Order History - The Clothing Store.
{% endblock %}
{% block content %}

<section class="accessory section bd-container" id="accessory">
    <div class="category__container   main__container container__grid">
         
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">Order History</h1>
            <br>
            {% if order_details %}
            <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Order Number</th>
                            <th>Order Date</th>
                            <th>Total Amount</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in order_details %}
                        <tr>
                            <td>{{ order.id }}</td>
                            <td>{{ order.created|date:"d M Y" }}</td>
                            <td>{{ order.total }}</td>
                            <td><i class="fas fa-check"></i>&nbsp;Complete</td>
                            <td><a href="{% url 'order:order_detail' order.id %}">View order</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
            </table>
            {% else %}
            <p>You have not placed any orders yet.<br><br><a href="#"
                                            class="btn btn-secondary">Continue
shopping</a></p>
            {% endif %}
        </div>
    </div>
    <br>
    <br>
    </div>
    </section>


{% endblock %}