accounts/urls.py
from . import views
from django.urls import path
from .views import UserEditView, myprofile, signup

app_name = 'accounts'

urlpatterns = [
    path('myprofile/', myprofile, name='myprofile'),
    path('signup/', signup, name='signup'),
    path("customer_service", views.contact, name="customer_service"),
    path('edit_profile/', UserEditView.as_view(), name='edit_profile'),
    path("wishlist", views.wishlist, name="wishlist"),
    path('wishlist/add_to_wishlist/<str:id>',
         views.add_to_wishlist, name='user_wishlist'),
]

cart/urls.py
from struct import pack
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/',
         views.full_remove, name='full_remove')

]

clothing_store/urls.py
from . import views
from newsletter.api import api_add_subscriber
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop.views import product_detail, category_detail, review_rate, Shop__All__Products

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('vendors/', include('vendors.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('vouchers/', include('vouchers.urls')),
    path('review/', review_rate, name='review'),
    path('api/add_subscriber/', api_add_subscriber, name='api_add_subscriber'),


    # SHOP
    path('shop_products', Shop__All__Products.as_view(), name='shop_products'),

    # SHOP

    path('<slug:category_slug>/<slug:slug>/',
         product_detail, name='product_detail'),
    path('<slug:slug>/',
         category_detail, name='category_detail'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search_app/urls.py
from django.urls import path
from .views import SearchResultsListView

app_name='search_app'

urlpatterns = [
    path('', SearchResultsListView.as_view(), name='searchResult'),
]

vendors/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

app_name = 'vendors'

urlpatterns = [
    path('new_vendor', views.new_vendor, name="new_vendor"),
    path('vendor_admin/', views.vendors_admin, name='vendor_admin'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit-vendor/', views.edit_vendor, name='edit_vendor'),
    path('edit-product/<str:pk>/', views.edit_product, name='edit_product'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='vendor/login.html'), name='login'),
    path('', views.vendors, name='vendors'),
    path('<int:vendor_id>/', views.vendor, name='vendor'),
]

shop/models.py
import uuid
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from vendors.models import Vendor
from vouchers.models import Voucher
from io import BytesIO
from PIL import Image
from django.core.files import File
from django.utils.text import slugify 


class Category(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    parent = models.ForeignKey(
        'self', related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(default="", max_length=255)
    ordering = models.IntegerField(default=0)
    is_featured = models.BooleanField(default=False)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'categories'
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/%s/' % (self.slug)


class Product(models.Model):
    MEDIUM = "M"
    YELLOW = "Yellow"
    COLOR = (("Yellow", 'Yellow'), ("Red", 'Red'), ("Green", 'Green'), ("Orange", 'Orange'), ("Black", 'Black'))
    SIZE = (("XL", 'XL'), ("L", 'L'), ("M", 'M'), ("S", 'S'), ("XS", 'XS'))
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    category = models.ForeignKey(
        Category, related_name='products', on_delete=models.CASCADE)
    vendor = models.ForeignKey(
        Vendor, blank=True, null=True, related_name='products', on_delete=models.CASCADE)
    parent = models.ForeignKey(
        'self', related_name='variants', on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='uploads/', blank=True, null=True)
    image1 = models.ImageField(upload_to='uploads/', blank=True, null=True)
    image2 = models.ImageField(upload_to='uploads/', blank=True, null=True)
    image3 = models.ImageField(upload_to='uploads/', blank=True, null=True)
    width = models.FloatField(default=300)
    length = models.FloatField(default=300)
    stock = models.IntegerField()
    size = models.CharField(max_length=6,choices=SIZE,default=MEDIUM, null=True)
    color = models.CharField(max_length=20,choices=COLOR,default=YELLOW, null=True)
    available = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)
    slug = models.SlugField(default="", max_length=255)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(default=timezone.now)
    visits = models.IntegerField(default=0)
    last_visit = models.DateTimeField(blank=True, null=True)
    voucher = models.ForeignKey(
        Voucher, default='', blank=True, null=True, on_delete=models.CASCADE)
    users_wishlist = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='user_wishlist', blank=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/%s/%s/' % (self.category.slug, self.slug)


class Review(models.Model):
    user = models.ForeignKey(
        User, related_name='review',  on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name='review', on_delete=models.CASCADE)
    comment = models.TextField(max_length=250, blank=True, null=True)
    stars = models.IntegerField(default=0)
    date_added = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.id)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
         <!--========== VUE JS ==========-->
         <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

         <!--========== BOX ICONS ==========-->
         <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
     
         <!--========== FONTAWESOME ==========-->
         <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css" />
         <!--========== BOOTSTRAP CDN ==========-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
         
         <!--========== CSS ==========-->
         <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
     

    <title>FULL.STOP - The Clothing Shop | Ireland's No.1 Online Shoppping destination</title>
</head>

<body>
    <!--========== SCROLL TOP ==========-->
    <a href="#" class="scrolltop" id="scroll-top">
        <i class='bx bx-up-arrow-alt scrolltop__icon'></i>
    </a>

    <!--========== HEADER ==========-->
    <header class="l-header" id="header">
        <nav class="nav bd-container">
            <a href="/" class="float__left">
                <img class="logo" src="{% static './images/logo.png' %}" alt="logo">
            </a>
            
            <div class="nav__menu" id="nav-menu">
                <ul class="nav__list float__left">
                    <li class="nav__item"><a href="/" class="nav__link active-link">Home</a></li>
                    <li class="nav__item"><a  href="{% url 'shop_products' %}"class="nav__link">Shop</a></li>
                    {% for category in menu_links %}
                    {% if not category.children.all %}
                    <li class="nav__item"><a href="{% url 'category_detail' category.slug %}" class="navbar-item">{{
                            category.name }}</a></li>
                    {% else %}
                    <li class="drop">
                        <a href="{% url 'category_detail' category.slug %}" class="nav__link drop__button">{{ category.name }}</a>

                        <div class="drop__menu">
                            {% for subcategory in category.children.all %}
                            <a href="{% url 'category_detail' subcategory.slug %}" class="nav__link">{{ subcategory.name }}</a>
                            {% endfor %}
                        </div>
                    </li>
                    {% endif %}
                    {% endfor %}

                    {% if request.user.vendor.is_vendor  %}
                    
                    <li class="nav__item"><a class="alt__button" href="{% url 'vendors:vendor_admin' %}">Vendor Admin</a></li>
                    {% else %}
                    <li class="nav__item"><a class="alt__button" href="{% url 'vendors:new_vendor' %}">New Vendor</a></li>
                    {% endif %}

                        <a href="{% url 'cart:cart_detail' %}" class="navbar-item ml">
                            <div class="navbadge">

                                <i class='bx bx-shopping-bag bx__icon'></i>
                                <span class="noti">{{item_count}}</span>

                            </div>
                        </a>
                        <a href="{% url 'accounts:wishlist' %}" class="navbar-item">
                            <div class="navbadge">

                                <i class='bx bx-heart bx__icon'></i>
                                {% if user.is_authenticated %}
                                <span class="noti">{{wishlist_count}}</span>
                                {% else %}
                                <span class="noti">0</span>
                                {% endif %}
                            </div>
                        </a>

                        {% if user.is_authenticated %}
                        <li class="drop">
                            {% if user.profile.image %}
                            <a class="navbar__link"><img src="{{ user.profile.image.url }}" alt="account"></a>
                            {% else %}
                            <a class="navbar__link"><img src="{% static './images/avatar.png' %}" alt="account"></a>
                            {% endif %}
                            
                            <div class="drop__menu">
                                <a class="nav__link" href="{% url 'accounts:myprofile' %}">View
                                    Profile</a>
                                <a class="nav__link" href="{% url 'accounts:edit_profile' %}">Edit
                                    Profile</a>
                                <a class="nav__link" href="{% url 'password_change'%}">Change Password</a>
                                <a class="nav__link" href="{% url 'logout' %}">Logout</a>
                            </div>
                        </li>
                        {% else %}
                        <li class="drop">
                            <a class="navbar-link" href="#"><i class='bx bx-user-circle bx__icon'></i></a>

                            <div class="drop__menu">
                                <a class="nav__link" href="{% url 'accounts:signup' %}">Sign Up</a>
                                <a class="nav__link" href="{% url 'login' %}">Login</a>
                            </div>
                        </li>
                        
                        {% endif %}
                        <li><i class='bx bx-toggle-left change-theme' id="theme-button"></i></li>
                </ul>



            </div>

            <div class="nav__toggle" id="nav-toggle">
                <i class='bx bx-grid-alt'></i>
            </div>
        </nav>
    </header>

    <main class="l-main">
        {% block content %}

        {% endblock %}
        </div>

           <!--========== FOOTER ==========-->
           <footer class="footer section">
            <div class="footer__container main__container container__grid border-bottom mb-5">
                <div class="footer__content">
                    <h3 class="footer__title">About</h3>
                    <ul>
                        <li><a href="#" class="footer__link">Pricing </a></li>
                        <li><a href="#" class="footer__link">Discounts</a></li>
                        <li><a href="{% url 'vendors:vendors' %}" class="footer__link">Vendors</a></li>
                    </ul>
                </div>

                <div class="footer__content">
                    <h3 class="footer__title">Our Services</h3>
                    <ul>
                        <li><a href="#" class="footer__link">Pricing </a></li>
                        <li><a href="#" class="footer__link">Discounts</a></li>
                        <li><a href="#" class="footer__link">Shipping mode</a></li>
                        <li><a href="{% url 'accounts:customer_service' %}" class="footer__link">Customer Service</a></li>
                    </ul>
                </div>


                <div class="footer__content mb-5">
                    <h3 class="footer__title">Social</h3>
                    <a href="#" class="footer__social"><i class='bx bxl-facebook-circle '></i></a>
                    <a href="#" class="footer__social"><i class='bx bxl-twitter'></i></a>
                    <a href="#" class="footer__social"><i class='bx bxl-instagram-alt'></i></a>
                    
                    {% include 'parts/newsletter.html' %}
                </div>
            </div>
            <hr>

            <p class="footer__copy">&#169; 2022 Clothing Shop. All right reserved</p>
        </footer>



   {% block scripts %}
        <!--========== VUEX JS ==========-->
        <script src="https://unpkg.com/vuex@3.5.1/dist/vuex.js"></script>

        <!--========== SCROLL REVEAL ==========-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--========== JS LINK ==========-->
        <script src="{% static 'js/script.js' %}" type="text/javascript"></script>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        {% endblock %}

</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}FULL.STOP - The Clothing Shop{% endblock %}

{% block content %}

<!--========== HOME ==========-->
<section class="home" id="home">
   
    <div class="home__rows main__container ">
        <form class="search__sidebar", action="{% url 'search_app:searchResult' %}" method="get">
            <input
              type="search"
              class="subscribe__input"
              me-2
              placeholder="Search products..."
              aria-label="Search"
              name="q"
            />
            <button class="main__button" type="submit">Search</button>
          </form>

          <div class="home__container">
            <div class="home__img">
                <img src="./static/images/trolly.webp" alt="">
            </div>
    
            <div class="home__data">
                <h1 class="home__title">All things clothing and Accessories</h1>
                <p class="home__description">Shop quality wears for various occassion. Choose from various categories of
                    high quality Italian wears and accessories.</p>
                <a href="./shop_products" class="main__button">Shop Now &#8594;</a>
            </div>
        </div>

    </div>
   
</section>


<!--========== CATEGORY ==========-->
<section class=" section">
    <div class="category__container   main__container container__grid">
        <div class="category__content">
            <h4 class="section-title-center category__title">Categories</h4>
            <div class="category_box">
                <div class="cats">
                    <img src="./static/images/men.webp" alt="">
                    <h3><a href="./men/" class="main__button button-link">Men</a></h3>
                </div>
                <div class="cats">
                    <img src="./static/images/woman.webp" alt="">
                    <h3><a href="./women/" class="main__button button-link">Women</a></h3>
                </div>
                <div class="cats">
                    <img src="./static/images/glasses.webp" alt="">
                    <h3><a href="./accessories/" class="main__button button-link">Accessories</a></h3>
                </div>
                <div class="cats">
                    <img src="./static/images/boy.webp" alt="">
                    <h3><a href="./boys/" class="main__button button-link">Boys</a></h3>
                </div>
                <div class="cats">
                    <img src="./static/images/girl.webp" alt="">
                    <h3><a href="./girls/" class="main__button button-link">Girls</a></h3>
                </div>
                <div class="cats">
                    <img src="./static/images/kids.webp" alt="">
                    <h3><a href="./Kids/" class="main__button button-link">Kids</a></h3>
                </div>
            </div>
        </div>
</section>

<!--========== FEATURED CATEGORIES ==========-->
<section class="section main__container" id="featured">
    <div class="section_heading">
        <h4 class="section-title">Featured Categories</h4>
        <h5 class="view_all"><a href="./shop_products">See All<span><i class='bx bx-chevron-right'></i></span></a></h5>
    </div>
    <div class="featured__container container__grid">
        {% for category in featured_categories %}
        <div class="featured__data">
            {% if category.image %}
            <img src="{{ category.image.url }}" alt="" class="featured__img">
            {% endif %}
            <h3 class="featured__title">{{ category.name }}</h3>

            <a href="./shop_products" class="main__button button-link">Shop Now &#8594;</a>
        </div>
        {% endfor %}
    </div>
</section>

<!-- ========== EXPLORE  ========== -->
<section class="subscribe section">
    <div class="explore_container main__container container__grid">
        <div class="explore__content">
            <h2 class="section-title-center subscribe__title">Explore High Quality At Unbeatable<br> Prices And Fast
                delivery</h2>
            <a href="./shop_products" class="main__button">Shop Now &#8594;</a>
        </div>
    </div>
</section>

<!--========== ACCESSORIES ==========-->
<section class="accessory section main__container" id="accessory">

    <div class="section_heading">
        <h4 class="section-title">Featured Products</h4>
        <h5 class="view_all"><a href="./shop_products">See All<span><i class='bx bx-chevron-right'></i></span></a></h5>
    </div>

    {% with products as list_products %}
    {% include 'parts/product_list.html' %}
    {% endwith %}
</section>

<!--========== EXPLORE ==========-->
<section class=" section">
    <div class="subscribe__container explore__container main__container container__grid">
        <div class="explore__content">
            <h2 class="section-title-center subscribe__title"> Sell Online with Admin page fully <br>customized  for you and pay a token<br> for sales</h2>
            <a href="{% url 'vendors:vendor_admin' %}" class="main__button">Shop Now &#8594;</a>
        </div>

        <div class="explore">

        </div>
    </div>
</section>

<section class="accessory section main__container" id="accessory">
    <div class="section_heading">
        <h4 class="section-title">Popular Products</h4>
        <h5 class="view_all"><a href="./shop_products">See All<span><i class='bx bx-chevron-right'></i></span></a></h5>
    </div>
    {% with popular_products as list_products %}
    {% include 'parts/product_list.html' %}
    {% endwith %}
</section>

<!--========== SUBSCRIBE ==========-->
<section class="subscribe section">
    <div class="subscribe__container main__container container__grid">
        <div class="explore__content ">
            <h2 class="section-title-center subscribe__title">Be among the first to know about new arrivals</h2>
          
                {% include 'parts/newsletter.html' %}
        </div>
    </div>
</section>


<section class="accessory section main__container" id="accessory">
    <div class="section_heading">
        <h4 class="section-title">Recently Viewed Products</h4>
        <h5 class="view_all"><a href="./shop_products">See All<span><i class='bx bx-chevron-right'></i></span></a></h5>
    </div>

    {% with recently_viewed_products as list_products %}
    {% include 'parts/product_list.html' %}
    {% endwith %}
</section>




{% endblock content %}